
# Syntax highlighting
markdown:            redcarpet
highlighter:         pygments

# Permalinks
permalink:           /:title
relative_permalinks: true

# Setup
timezone:            America/Sao_Paulo
locale:              pt_BR
name:				 bleidi.me
title:               bleidi.me
tagline:             'bleidi.me'
description:         'On this life that we call home the years go fast and the days go so slow'
url:                 http://bleidi.me
rss:                 rss feed url
baseurl:             '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
#icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              bleidi-me

author:
  name:           	 'Rafael Souuza Oliveira'
  url:            	 http://bleidi.me
  facebook:          rafaelbleidi
  twitter:           rafaelbleidi

#fb_admins:           your facebook profile id
#fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
